### PR TITLE
Fixed the error when Empty main runs with VerTracker

### LINKED ISSUE #380: The `VarTracker` listener always throws an `ArrayIndexOutOfBoundsException` exception
Using the `VarTracker` listener results in an `ArrayIndexOutOfBoundsException`. Here is (the smallest possible) example that can cause this:
```java
public class Test {
  public static void main(String[] args) {}
}
```

The error:
```
[WARNING] orphan NativePeer method: jdk.internal.misc.Unsafe.getUnsafe()Lsun/misc/Unsafe;
[SEVERE] JPF exception, terminating: exception during instructionExecuted() notification
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
        at gov.nasa.jpf.vm.StackFrame.addOperandAttr(StackFrame.java:533)
        at gov.nasa.jpf.listener.VarTracker.instructionExecuted(VarTracker.java:194)
        at gov.nasa.jpf.vm.VM.notifyInstructionExecuted(VM.java:807)
        at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1925)
        at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1861)
        at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
        at gov.nasa.jpf.vm.VM.forward(VM.java:1721)
        at gov.nasa.jpf.search.Search.forward(Search.java:579)
        at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
        at gov.nasa.jpf.JPF.run(JPF.java:613)
        at gov.nasa.jpf.JPF.start(JPF.java:189)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at gov.nasa.jpf.tool.Run.call(Run.java:80)
        at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
---------------------- JPF error stack trace ---------------------
gov.nasa.jpf.JPFListenerException: exception during instructionExecuted() notification
        at gov.nasa.jpf.vm.VM.notifyInstructionExecuted(VM.java:814)
        at gov.nasa.jpf.vm.ThreadInfo.executeInstruction(ThreadInfo.java:1925)
        at gov.nasa.jpf.vm.ThreadInfo.executeTransition(ThreadInfo.java:1861)
        at gov.nasa.jpf.vm.SystemState.executeNextTransition(SystemState.java:765)
        at gov.nasa.jpf.vm.VM.forward(VM.java:1721)
        at gov.nasa.jpf.search.Search.forward(Search.java:579)
        at gov.nasa.jpf.search.DFSearch.search(DFSearch.java:79)
        at gov.nasa.jpf.JPF.run(JPF.java:613)
        at gov.nasa.jpf.JPF.start(JPF.java:189)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at gov.nasa.jpf.tool.Run.call(Run.java:80)
        at gov.nasa.jpf.tool.RunJPF.main(RunJPF.java:116)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
        at gov.nasa.jpf.vm.StackFrame.addOperandAttr(StackFrame.java:533)
        at gov.nasa.jpf.listener.VarTracker.instructionExecuted(VarTracker.java:194)
        at gov.nasa.jpf.vm.VM.notifyInstructionExecuted(VM.java:807)
        ... 14 more
```

The values of `top`, `stackBase` and `Object a` in `StackFrame.addOperandAttr(a)` when this exception is hit:
* `top`: `-1`
* `stackBase`: `0`
* `a`: `UNSAFE`

### PR DESCRIPTION
**Pull request by shreyasCs012**
### Description  : 

  This PR fixes the error when we run an empty main set to a VerTracker listener. 

### Issue Fixed :
  
  #380

### Testing :
  
    I added a test that calls the empty main method setting the listener to VerTracker.

###Fix :

  -  The error was reflected because the addOperandAttr() method was called in the VerTracker without checking if the 
       operand stack was empty.

  -  The if condition `(frame.getTopPos() >= 0)` checks for the above undetected condition.

### CODE REVIEW

File: src/main/gov/nasa/jpf/listener/VarTracker.java [hunk 1]
```diff
@@ -191,7 +191,9 @@ public void instructionExecuted(VM vm, ThreadInfo ti, Instruction nextInsn, Inst
       varId = ((JVMFieldInstruction)executedInsn).getFieldName();
 
       StackFrame frame = ti.getModifiableTopFrame();
-      frame.addOperandAttr(varId);
+      if (frame.getTopPos() >= 0) {
```
Comment (cyrille-artho) [inline src/main/gov/nasa/jpf/listener/VarTracker.java:194]: I think this check is also needed a few lines above (after line 185), as I don't think we can be sure that there is a local variable in all cases where that line is hit.
WDYT?

**Comment by cyrille-artho** [comment]
Looks good! I think we need the same check in both places where `addOperandAttr` is called; see my comment.
We unfortunately don't have a test to ascertain this, though.

**Comment by shreyasCs012** [comment]
I think Before the call for `addOperandAttr(varId);` there is a call for the `peek() ` method which from the look of it returns the element in the slots array 
```
 public int peek () {
    return slots[top];
  }
```
if the top value does not change before any call for the  `addOperandAttr(varId);` method then either an error should hit in that call for the ` peek() ` method or if the error does not hit there should be no problem when the call for  `addOperandAttr(varId);` is made.

`Again I am assuming that the top variable is not changing.`

**Comment by cyrille-artho** [comment]
Good observation. I noticed now also that the instruction must be ALOAD, which means that there is a local variable slot available (because the bytecode verifier would have rejected the code earlier, when it was verified after loading, if that were not the case).
We can therefore merge this PR as it is. Thank you very much for your work!

**Review by cyrille-artho — APPROVED** [review]
